jobs:
  include:
    - #stage: PostgreSQL 10
      name: "PostgreSQL 10"
      env:
        - PGVERSION=pg10
      script: ./.travis_build_script.yml
    - #stage: PostgreSQL 11
      name: "PostgreSQL 11"
      env:
        - PGVERSION=pg11
      script: ./.travis_build_script.yml
    - # stage: PostgreSQl 12
      name: "PostgreSQL 12"
      env:
        - PGVERSION=pg12
      script: ./.travis_build_script.yml
